// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from prahazijehudbou.djinni

#pragma once

#include "djinni_support.hpp"
#include "praha_zije_hudbou.hpp"

namespace djinni_generated {

class NativePrahaZijeHudbou final : ::djinni::JniInterface<::prahazijehudbou::PrahaZijeHudbou, NativePrahaZijeHudbou> {
public:
    using CppType = std::shared_ptr<::prahazijehudbou::PrahaZijeHudbou>;
    using CppOptType = std::shared_ptr<::prahazijehudbou::PrahaZijeHudbou>;
    using JniType = jobject;

    using Boxed = NativePrahaZijeHudbou;

    ~NativePrahaZijeHudbou();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativePrahaZijeHudbou>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativePrahaZijeHudbou>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativePrahaZijeHudbou();
    friend ::djinni::JniClass<NativePrahaZijeHudbou>;
    friend ::djinni::JniInterface<::prahazijehudbou::PrahaZijeHudbou, NativePrahaZijeHudbou>;

};

}  // namespace djinni_generated
