// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from prahazijehudbou.djinni

#include "NativePrahaZijeHudbou.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativePrahaZijeHudbou::NativePrahaZijeHudbou() : ::djinni::JniInterface<::prahazijehudbou::PrahaZijeHudbou, NativePrahaZijeHudbou>("net/blindchamaleonstudio/prahazijehudbou/PrahaZijeHudbou$CppProxy") {}

NativePrahaZijeHudbou::~NativePrahaZijeHudbou() = default;


CJNIEXPORT void JNICALL Java_net_blindchamaleonstudio_prahazijehudbou_PrahaZijeHudbou_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<::djinni::CppProxyHandle<::prahazijehudbou::PrahaZijeHudbou>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_net_blindchamaleonstudio_prahazijehudbou_PrahaZijeHudbou_00024CppProxy_create(JNIEnv* jniEnv, jobject /*this*/)
{
    try {
        DJINNI_FUNCTION_PROLOGUE0(jniEnv);
        auto r = ::prahazijehudbou::PrahaZijeHudbou::create();
        return ::djinni::release(::djinni_generated::NativePrahaZijeHudbou::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jstring JNICALL Java_net_blindchamaleonstudio_prahazijehudbou_PrahaZijeHudbou_00024CppProxy_native_1getHelloWorld(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::prahazijehudbou::PrahaZijeHudbou>(nativeRef);
        auto r = ref->get_hello_world();
        return ::djinni::release(::djinni::String::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

}  // namespace djinni_generated
