// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from prahazijehudbou.djinni

#import <Foundation/Foundation.h>
@class HWPrahaZijeHudbou;


@interface HWPrahaZijeHudbou : NSObject

+ (nullable HWPrahaZijeHudbou *)create;

- (nonnull NSString *)getHelloWorld;

@end
