// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from prahazijehudbou.djinni

#pragma once

#include <memory>
#include <string>

namespace prahazijehudbou {

class PrahaZijeHudbou {
public:
    virtual ~PrahaZijeHudbou() {}

    static std::shared_ptr<PrahaZijeHudbou> create();

    virtual std::string get_hello_world() = 0;
};

}  // namespace prahazijehudbou
